version: "3.3"

services:

  wordpress:
    image: wordpress
    container_name: "${PROJECT_NAME}_wordpress"
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
      - wordpress:/var/www
    depends_on:
      - db

  db:
    image: mysql
    container_name: "${PROJECT_NAME}_db"
    restart: always
    ports:
      - 3306:3306
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql

  php:
    image: php:8.0
    container_name: "${PROJECT_NAME}_php"
    environment:
      SSMTP_MAILHUB: mailhog:1025
      PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -f -t"'
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    #      # Read instructions at https://wodby.com/docs/stacks/wordpress/local#xdebug
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_MODE: debug
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_IDEKEY: "my-ide"
    #      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
    #      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows
    #      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www:cached

  nginx:
    image: nginx
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - 90:80
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
    volumes:
      - ./:/var/www:cached
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
    depends_on:
      - php

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"
    depends_on:
      - db

volumes:
  wordpress:
    driver: local
  db:
    driver: local